# Generated by Django 2.2.23 on 2021-05-31 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sso_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Identifiant unique"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nom de la bibliothèque / médiathèque",
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        null=True, verbose_name="Date de fin d'abonnement"
                    ),
                ),
                (
                    "connector",
                    models.CharField(
                        choices=[
                            ("GMINVENT", "GMInvent"),
                            ("C3RB", "C3rb"),
                            ("ARCHIMED", "Archimed"),
                        ],
                        default="GMInvent",
                        max_length=20,
                        verbose_name="Connecteurs",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
