# Generated by Django 2.2.24 on 2021-10-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='sso_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Identifiant unique'),
        ),
    ]
